version: 2

jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: apk --no-cache --no-progress add bash make
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWD}
      - run: make

workflows:
  version: 2
  build:
    jobs:
      - build
